### ISSUE TITLE
Two work items were created for the same GitHub issue

### ISSUE THREAD

**Issue by edmorley** [forcedotcom/git2gus#97]
Hi!

I created https://github.com/heroku/heroku-buildpack-python/issues/1060 and then added the `gus: story` GitHub label that I've set up to be for User Stories.

The Git2Gus bot then successfully created:
https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008XaA0IAK/view

A few minutes later I added another label to the GitHub issue, at which point Git2Gus unexpectedly created a second unwanted User Story:
https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008XaAnIAK/view

It's not clear why this occurred.

The config for the repo in question is here:
https://github.com/heroku/heroku-buildpack-python/blob/ab69658efbdb3addf7b2e155ebb5bb6e518a597c/.git2gus/config.json

**Comment by edmorley** [comment]
This happened again in:
https://github.com/heroku/heroku-buildpack-python/issues/1067

This issue makes Git2Gus pretty unusable right now unfortunately - since it appears I can't add any additional labels without causing duplicates.

**Comment by edmorley** [comment]
Both of the work items contain the correct related URL for what it's worth:

```
$ sfdx force:data:record:get -s ADM_Work__c -i a07B0000008dLYJIA2 --json | jq '.result.Related_URL__c'
"https://github.com/heroku/heroku-buildpack-python/issues/1067"

$ sfdx force:data:record:get -s ADM_Work__c -i a07B0000008dLYdIAM --json | jq '.result.Related_URL__c'
"https://github.com/heroku/heroku-buildpack-python/issues/1067"
```

**Comment by edmorley** [comment]
Any news on this? I've stopped using Git2Gus because of this issue.

**Comment by lpomerleau** [comment]
Following this issue. I am seeing the same on these repos:
- https://github.com/salesforce/lwr
- https://github.com/salesforce/lwr-ui
- https://github.com/salesforce/lwr-recipes
